#ifndef QQMLSORTFILTERPROXYMODEL_EXPORT_H
#define QQMLSORTFILTERPROXYMODEL_EXPORT_H

#include <QtCore/qglobal.h>

#if defined(SORT_FILTER_PROXY_MODEL_LIBRARY_BUILD)
#  define QQMLSORTFILTERPROXYMODEL_EXPORT Q_DECL_EXPORT
#else
#  define QQMLSORTFILTERPROXYMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // QQMLSORTFILTERPROXYMODEL_EXPORT_H
